CREATE TABLE CUSTOMER
(
    CID CHAR(9) NOT NULL,
    First VARCHAR(20),
    Last VARCHAR(20),
    State CHAR(2),
    City VARCHAR(20),
    ZIP CHAR(5),
    Street VARCHAR(25),
    PRIMARY KEY (CID)
);
CREATE TABLE PAYMENT_METHODS
(
    CID CHAR(9) NOT NULL,
    Nickname VARCHAR(20) NOT NULL,
    PaymentType VARCHAR(15),
    PRIMARY KEY (CID, Nickname),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
);
CREATE TABLE MERCHANDISE
(
    MID CHAR(9) NOT NULL,
    PRIMARY KEY (MID)
);
CREATE TABLE BUYS
(
    CID CHAR(9) NOT NULL,
    MID CHAR(9) NOT NULL,
    Quantity INT,
    PRIMARY KEY (CID, MID),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID),
    FOREIGN KEY (MID) REFERENCES MERCHANDISE(MID)
);
CREATE TABLE VIDEO_GAME
(
    UPC CHAR(12) NOT NULL,
    MID CHAR(9),
    Rating VARCHAR(5),
    Platform VARCHAR(20),
    PRIMARY KEY (UPC),
    FOREIGN KEY (MID) REFERENCES MERCHANDISE(MID)
);
CREATE TABLE BOOKS
(
    ISBN CHAR(13) NOT NULL,
    MID CHAR(9),
    Genre VARCHAR(20),
    PRIMARY KEY (ISBN),
    FOREIGN KEY (MID) REFERENCES MERCHANDISE(MID)
);
CREATE TABLE AUTHORS
(
    ISBN CHAR(13) NOT NULL,
    Author VARCHAR(20) NOT NULL,
    PRIMARY KEY (ISBN, Author),
    FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);
CREATE TABLE COMICS
(
    ISBN CHAR(13) NOT NULL,
    Artist VARCHAR(20),
    PRIMARY KEY (ISBN),
    FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);
CREATE TABLE STORE
(
    License VARCHAR(20) NOT NULL,
    Name VARCHAR(20),
    Phone CHAR(11),
    State CHAR(2),
    City VARCHAR(20),
    ZIP CHAR(5),
    Street VARCHAR(25),
    PRIMARY KEY (License)
);
CREATE TABLE HAS
(
    License VARCHAR(20) NOT NULL,
    MID CHAR(9) NOT NULL,
    Quantity INT,
    PRIMARY KEY (License, MID),
    FOREIGN KEY (License) REFERENCES STORE,
    FOREIGN KEY (MID) REFERENCES MERCHANDISE(MID)
);

CREATE OR REPLACE FUNCTION check_customer_address()
RETURNS TRIGGER AS $check_customer_address$
    BEGIN
        IF (NEW.state IS NULL) OR (NEW.city IS NULL) OR (NEW.zip IS NULL) OR (NEW.street IS NULL) THEN
        RAISE EXCEPTION 'Enter a valid address.';
        END IF;
    END;
    $check_customer_address$ LANGUAGE plpgsql;

CREATE TRIGGER check_customer_address
    BEFORE INSERT ON CUSTOMER
    FOR EACH ROW
    EXECUTE PROCEDURE check_customer_address();